---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.19.36
  
platforms:
  - name: centos-6.5
    driver_config:
      network:
      - ["private_network", {ip: "33.33.33.22"}]

suites:
  - name: default
    run_list:
      - recipe[cb_steveApp::default]
    attributes:
